on:
  workflow_call:
    inputs:
      module_version:
        type: string
        description: "The version of the module to release"
        required: true

jobs:
  release:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: prebuilds

      - run: |
          mkdir -p artifacts
          for folder in prebuilds/*/; do
            folder_name=$(basename "$folder")
            tar -czvf "artifacts/${folder_name}.tar.gz" -C "prebuilds/${folder_name}"
          done

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*"
          artifactErrorsFailBuild: true
          allowUpdates: true
          replacesArtifacts: true
          tag: ${{ inputs.module_version }}
